# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


r_packages:
  - testextra
  - covr
  - roxygen2

before_script:
  - Rscript -e 'testextra::extract_tests()'
  - Rscript -e 'roxygen2::roxygenise(".", "rd")'

after_success:
  - Rscript -e 'covr::codecov()'
